### ISSUE TITLE
After update: only empty space in systray

### ISSUE THREAD

**Issue by kinoegit** [bouteillerAlan/archupdate#34]
Operating System: Arch Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.7.8-arch1-1 (64-bit)
Graphics Platform: X11
Graphics Processor: Mesa Intel® UHD Graphics 630

AUR package: kdeplasma-arch-update-notifier-git

After update from 4.2.1 to 5.0.1 the icon and any clicking function disappeared. Only an empty space is shown when "Shown when relevant" or "Always shown" is selected

Journald log reported:
`plasmashell: file:///usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/items/PlasmoidItem.qml:123:5: QML Connections: Detected function "onContainsPressChanged" in Connections element. This is probably intended to be a signal handler but no signal of the "PlasmoidItem_QMLTYPE_1214" target matches the name.`

`plasmashell: file:///usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/items/PlasmoidItem.qml:123:5: QML Connections: Detected function "onPressAndHold" in Connections element. This is probably intended to be a signal handler but no signal of the "PlasmoidItem_QMLTYPE_1214" target matches the name.`

`plasmashell: file:///usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/items/PlasmoidItem.qml:125: TypeError: Cannot read property 'compactRepresentationItem' of null`

**Comment by bouteillerAlan** [comment]
Hi, I move too fast for KDE plasma 6, I revert the package to `4.2.1-1`, the new version is `5.0.2`.

After an update everithing should be working, keep me in touch if yes or no please :)

**Comment by bouteillerAlan** [comment]
Hey, sorry for the mess, like I said I have updated the package on the AUR a little too soon because plasma 6 is still on testing on the extra repository. Because of that, I have screwed up the package this morning, my bad for that ^^ 

So now we have two packages available in function of your plasma version : 
 - for plasma 5 : [kdeplasma5-arch-update-notifier-git](https://aur.archlinux.org/packages/kdeplasma5-arch-update-notifier-git)
 - for plasma 6 : [kdeplasma-arch-update-notifier-git](https://aur.archlinux.org/packages/kdeplasma-arch-update-notifier-git) 

Keep me in touch if everything is back to normal :)

**Comment by kinoegit** [comment]
Everything is back to normal, thanks a lot!
