### ISSUE TITLE
yay:  the git version will reinstall v4 (downgrade) instead of keeping v5

### ISSUE THREAD

**Issue by Mshmaitelly** [bouteillerAlan/archupdate#36]
![image](https://github.com/bouteillerAlan/archupdate/assets/13006192/56236dd3-0c3b-44b9-bcd2-9d8559b11eae)

**Comment by Mshmaitelly** [comment]
I removed the git version  (AUR package) and I installed from the KDE add widget. 
I hope this would help.

**Comment by bouteillerAlan** [comment]
Hi, I have updated the package on the AUR a little too soon because plasma 6 is still on testing on the extra repository. Because of that, I have screwed up the package this morning, my bad for that ^^ 

So now we have two packages available in function of your plasma version : 
 - for plasma 5 : [kdeplasma5-arch-update-notifier-git](https://aur.archlinux.org/packages/kdeplasma5-arch-update-notifier-git)
 - for plasma 6 : [kdeplasma-arch-update-notifier-git](https://aur.archlinux.org/packages/kdeplasma-arch-update-notifier-git)

**Comment by Mshmaitelly** [comment]
I will try to reinstall the git version

**Comment by bouteillerAlan** [comment]
Ok for some reason the package have kept the same id in the db (I think) so I have updated to v5.0.4, should be ok now. Thanks for your help :)

**Comment by bouteillerAlan** [comment]
![Screenshot_20240305_170944](https://github.com/bouteillerAlan/archupdate/assets/30547569/dee18f44-b5c3-4e31-98b6-79d88bb0fab8)

**Comment by bouteillerAlan** [comment]
Is everything working now @Mshmaitelly  ?
