### ISSUE TITLE
Plasma 6: no update option

### ISSUE THREAD

**Issue by kinoegit** [bouteillerAlan/archupdate#42]
After migrating to Plasma 6 following issues:
-- right click on icon in systray does only show config option NOT update button, even though updates are actually available and indicated
-- icon in systray is nearly invisible with darker plasma themes = black on black

**Comment by bouteillerAlan** [comment]
Hi, the first bug is fixed in the next release, I hope to ship it this day.

For the second, can you provide more information (current theme, a screenshot, ...) ? The color is set automatically via the plasma theme so, unless your current theme is not correct, everything should be fine. Example with the default dark theme :
![Screenshot_20240307_122121](https://github.com/bouteillerAlan/archupdate/assets/30547569/ae67e511-f042-4254-9e05-7452205665db)

**Comment by kinoegit** [comment]
Thanks, will tinker with config to test themes

**Comment by bouteillerAlan** [comment]
First bug release in https://github.com/bouteillerAlan/archupdate/releases/tag/v5.1.0

**Comment by kinoegit** [comment]
Thank you very much for your good work. Update function is well now. The icon issue is a bit strange, but I fiddled with costumization and finally got a workaround. Thing is: even though all icons in the systray did adapt with my favourite plasma theme only archupdate icon won't.
