### ISSUE TITLE
Icon invisible in panel with dark theme [plasma 6]

### ISSUE THREAD

**Issue by kinoegit** [bouteillerAlan/archupdate#46]
![xxx](https://github.com/bouteillerAlan/archupdate/assets/18682867/69370e79-ac72-4291-be2e-fe4087d328b2)
Panel icon is black on black with tested dark global themes (breeze dark & breeze twilight) and ca 20 different plasma themes, icon sets & color settings. View other icons (nextcloud and solaar) seem to have got the same issue. I wonder whether the issue has got to do with [porting to plasma 6](https://pointieststick.com/2023/08/12/how-all-this-icon-stuff-is-going-to-work-in-plasma-6/) ?

**Comment by bouteillerAlan** [comment]
Hey, what is your distro ? I need to dig this bug since I have a dark theme and everything is working fine ^^ 
![image](https://github.com/bouteillerAlan/archupdate/assets/30547569/c070c504-09ca-427d-b7d1-bfb193dab14f)

Thanks for the link, I read that and look if an update is needed ! (maybe today or tomorrow)

**Comment by kinoegit** [comment]
Sure:
Operating System: Arch Linux 
KDE Plasma Version: 6.0.1
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.7.9-arch1-1 (64-bit)
Graphics Platform: Wayland
Graphics Processor: Mesa Intel® UHD Graphics 630

**Comment by bouteillerAlan** [comment]
[On a side note, the color is set here.](https://github.com/bouteillerAlan/archupdate/blob/580c5f87d2a1bd5adcccbe466e09cb792a149052/a2n.archupdate.plasmoid/contents/ui/components/PlasmoidIcon.qml#L21)

**Comment by bouteillerAlan** [comment]
Ok I can reproduce with breeze twilight
![image](https://github.com/bouteillerAlan/archupdate/assets/30547569/b886bff8-4a61-45f0-963e-95a5b5b247d9)

**Comment by luisbocanegra** [comment]
I think the problem here is that Plasma only sets colors for named icons (those that come from the icon theme), and not to user selected ones (those that come from a absolute path or a Qt.resolvedUrl). Even when the icon has css colors correctly defined.

Maybe they do this with the assumption that the user may give a full-color icon or this could be a bug?

The alternative I found is to use Kirigami.Icon instead with `isMask: true`:

```qml
Kirigami.Icon {
    id: svgItem
    opacity: 1
    width: parent.width
    height: parent.height
    property int sourceIndex: 0
    anchors.centerIn: parent
    smooth: true
    isMask: true
    source: Qt.resolvedUrl("../../assets/" + root.source)
}
```

It has the downside of making the icons have a single color though so no accent/highlight etc. from the icon's css.

**Comment by bouteillerAlan** [comment]
Okai see #48

**Comment by kinoegit** [comment]
After yesterdays update of Plasma 6.0.2 the color issue of systray icons was fixed! So it was an upstream bug!?
