### ISSUE TITLE
archupdate keeps trying to update until checkupdate finds updatable package

### ISSUE THREAD

**Issue by Qweffe** [bouteillerAlan/archupdate#57]
it just keeps trying to update until `checkupdate` finds something
![obrazek](https://github.com/bouteillerAlan/archupdate/assets/105426376/4cce0786-54c0-4d5c-ba49-26b337c8ac0e)
and only stops when it finds something.

I don't know what those "==> ERROR: Cannot fetch updates\n" are about since the command works fine when i run it manually in terminal and i'm not running any firewalls that could block it.

**Comment by bouteillerAlan** [comment]
I investigate this situation, but it's pretty weird (somewhat related to #49 ) so it may take some time to be fix :/ 

I do my best & keep you in touch soon has the fix is available. 

PS : the cmd relaunch automatically the cmd that fail that what the code keep trying, I investigate the error because this is the problem

**Comment by bouteillerAlan** [comment]
Hey @Qweffe can you try the v6.1.5 and tell me if the problem persists ? (the pling store & aur are up-to-date)

Check if you are in the right version via the settings window : 
![image](https://github.com/bouteillerAlan/archupdate/assets/30547569/6d10930c-d73c-4249-9d7a-9d022580bd1d)

**Comment by Qweffe** [comment]
I updated and it works perfectly. Thanks!
