### ISSUE TITLE
App shows lines that do not match any updates.

### ISSUE THREAD

**Issue by Giger22** [bouteillerAlan/archupdate#65]
Hello, I use paru and I have an additional lines:
$ Paru -Sua
$ :: Looking for devel upgrades...
$ :: marked out of date: 
$ :: orphans: 
 there is nothing to do
[Image](https://i.imgur.com/m0rAMDG.png)

**Comment by bouteillerAlan** [comment]
Hello, sorry for the delay of my answer, I have some health issue atm.

This bug appends because the print of the cmd return additional line : 
![image](https://github.com/bouteillerAlan/archupdate/assets/30547569/9cb6d546-42f5-4069-a1e2-040336786a8e)

You need to use the `paru -Qua` cmd for the list :
![image](https://github.com/bouteillerAlan/archupdate/assets/30547569/fcf7593a-7b58-4043-990c-e40c8416e6eb)
